//
//  Resolver.swift
//  Generated by dikitgen.
//

import APIClient
import DIKit
import Foundation
import JSONExport
import ReactiveSwift

extension AppResolver {

    func resolveAppResolver() -> AppResolver {
        return provideResolver()
    }

    func resolveAreaFilterViewModel(selectedAreaTypes: [Area]) -> AreaFilterViewModel {
        return AreaFilterViewModel(dependency: .init(selectedAreaTypes: selectedAreaTypes))
    }

    func resolvePrefectureListViewModel() -> PrefectureListViewModel {
        let appResolver = resolveAppResolver()
        let weatherAPIClient = resolveWeatherAPIClient()
        return PrefectureListViewModel(dependency: .init(resolver: appResolver, apiClient: weatherAPIClient))
    }

    func resolveWeatherAPIClient() -> WeatherAPIClient {
        return provideAPIClient()
    }

    func resolveWeatherViewModel(weather: Weather, cityData: CityData) -> WeatherViewModel {
        let appResolver = resolveAppResolver()
        let weatherAPIClient = resolveWeatherAPIClient()
        return WeatherViewModel(dependency: .init(resolver: appResolver, apiClient: weatherAPIClient, weather: weather, cityData: cityData))
    }

}

