//
//  Resolver.swift
//  Generated by dikitgen.
//

import Alamofire
import DIKit
import Foundation
import ReactiveCocoa
import ReactiveSwift
import SVProgressHUD
import UIKit

extension AppResolver {

    func resolveAPIClient() -> APIClient {
        return provideAPIClient()
    }

    func resolveAreaFilterViewController(selectedAreaTypes: [Area]) -> AreaFilterViewController {
        let areaFilterViewModel = resolveAreaFilterViewModel(selectedAreaTypes: selectedAreaTypes)
        return AreaFilterViewController.makeInstance(dependency: .init(viewModel: areaFilterViewModel))
    }

    func resolveAreaFilterViewModel(selectedAreaTypes: [Area]) -> AreaFilterViewModel {
        return AreaFilterViewModel(dependency: .init(selectedAreaTypes: selectedAreaTypes))
    }

    func resolvePrefectureListViewController(resolver: AppResolver) -> PrefectureListViewController {
        let prefectureListViewModel = resolvePrefectureListViewModel(resolver: resolver)
        return PrefectureListViewController.makeInstance(dependency: .init(viewModel: prefectureListViewModel))
    }

    func resolvePrefectureListViewModel(resolver: AppResolver) -> PrefectureListViewModel {
        return PrefectureListViewModel(dependency: .init(resolver: resolver))
    }

    func resolveWeatherViewController(resolver: AppResolver, weather: Weather, cityData: CityData) -> WeatherViewController {
        let weatherViewModel = resolveWeatherViewModel(resolver: resolver, weather: weather, cityData: cityData)
        return WeatherViewController.makeInstance(dependency: .init(viewModel: weatherViewModel))
    }

    func resolveWeatherViewModel(resolver: AppResolver, weather: Weather, cityData: CityData) -> WeatherViewModel {
        return WeatherViewModel(dependency: .init(resolver: resolver, weather: weather, cityData: cityData))
    }

}

