# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SwiftArchitecture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftArchitecture
	pod 'SVProgressHUD'
	pod 'Alamofire'
	pod 'ReactiveCocoa', '~> 9.0'

  target 'SwiftArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftArchitectureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
